### ISSUE TITLE
not included "config.hpp" to the stat.hpp and sound.hpp made no_fmod options non working

### ISSUE THREAD

**Issue by kas1e** [ptitSeb/Barony#1]
While i tried to build version which didn't use fmod, but use openall instead, i found that those 2 files (stat.hpp and sound.hpp) do not have #include "Config.hpp" file , which in turn make non visibly for them undef for HAVE_FMOD and define for HAVE_OPENAL, so even if you provide in cmake arguments -DFMOD_ENABLED=OFF  it still didn't taken in account, as config file never included in those 2 files.

At least that was in CursedEdition, and seing in repo now after update, seems bug still here.

**Comment by ptitSeb** [comment]
Oh, correct. I'll fix that in a commit (but applied on current sources).
